//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Nev { get; set; }
        public string E_mail { get; set; }
        public Nullable<System.DateTime> Szuletesi_datum { get; set; }
        public string Telefon { get; set; }
        public string Cim { get; set; }
        public Nullable<System.DateTime> Rendeles_ideje { get; set; }
        public Nullable<int> Mennyiseg { get; set; }
        public Nullable<decimal> Egysegar { get; set; }
        public Nullable<decimal> Összesen { get; set; }
        public string Rendelt_termek { get; set; }
    }
}
